### ISSUE TITLE
Cannot build with ghc-9.2.2

### ISSUE THREAD

**Issue by WeetHet** [fjvallarino/monomer#159]
I'm currently trying to compile starter project on macOS 12.3, arm64. The following output of ```cabal build```
 appears ([log.txt](https://github.com/fjvallarino/monomer/files/8757522/log.txt) attached):

```
src/Monomer/Widgets/Containers/Dropdown.hs:423:3: error:
    • Illegal equational constraint Control.Lens.At.Index a2 ~ Int
      (Use GADTs or TypeFamilies to permit this)
    • When checking the inferred type
        scrollListInfo :: forall {s} {a1} {b} {a2} {p}.
                          (L.HasWidgetId s a1, L.HasPath s b, Control.Lens.At.Index a2 ~ Int,
                           L.HasChildren p a2, Control.Lens.At.Ixed a2,
                           L.HasInfo (Control.Lens.At.IxValue a2) s) =>
                          p -> (a1, b)
      In an equation for ‘makeDropdown’:
          makeDropdown widgetData items makeMain makeRow config state
            = widget
            where
                container
                  = def
                      {containerAddStyleReq = False,
                       containerChildrenOffset = Just (_ddsOffset state),
                       containerGetBaseStyle = getBaseStyle, containerInit = init,
                       containerFindNextFocus = findNextFocus,
                       containerFindByPoint = findByPoint, containerMerge = merge,
                       containerDispose = dispose, containerHandleEvent = handleEvent,
                       containerHandleMessage = handleMessage,
                       containerGetSizeReq = getSizeReq, containerResize = resize}
                baseWidget = createContainer state container
                widget = baseWidget {widgetRender = render}
                mainIdx = 0
                ....
    |
423 |   scrollListInfo node = (scrollInfo ^. L.widgetId, scrollInfo ^. L.path) where
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Monomer/Widgets/Containers/Dropdown.hs:426:3: error:
    • Illegal equational constraint Control.Lens.At.Index a2 ~ Int
      (Use GADTs or TypeFamilies to permit this)
    • When checking the inferred type
        selectListInfo :: forall {s} {a1} {b} {a2} {p} {a3}.
                          (L.HasWidgetId s a1, L.HasPath s b, Control.Lens.At.Index a2 ~ Int,
                           L.HasChildren p a2, L.HasChildren (Control.Lens.At.IxValue a2) a3,
                           Control.Lens.At.Ixed a2, Control.Lens.At.Ixed a3,
                           Num (Control.Lens.At.Index a3),
                           L.HasInfo (Control.Lens.At.IxValue a3) s) =>
                          p -> (a1, b)
      In an equation for ‘makeDropdown’:
          makeDropdown widgetData items makeMain makeRow config state
            = widget
            where
                container
                  = def
                      {containerAddStyleReq = False,
                       containerChildrenOffset = Just (_ddsOffset state),
                       containerGetBaseStyle = getBaseStyle, containerInit = init,
                       containerFindNextFocus = findNextFocus,
                       containerFindByPoint = findByPoint, containerMerge = merge,
                       containerDispose = dispose, containerHandleEvent = handleEvent,
                       containerHandleMessage = handleMessage,
                       containerGetSizeReq = getSizeReq, containerResize = resize}
                baseWidget = createContainer state container
                widget = baseWidget {widgetRender = render}
                mainIdx = 0
                ....
    |
426 |   selectListInfo node = (listInfo ^. L.widgetId, listInfo ^. L.path) where
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by WeetHet** [comment]
[log.txt](https://github.com/fjvallarino/monomer/files/8757522/log.txt)

**Comment by fjvallarino** [comment]
The error should be fixed by this PR: https://github.com/fjvallarino/monomer/pull/162. To test it, you need to modify your `stack.yaml` to point to:

```yaml
- git: https://github.com/fjvallarino/monomer.git
  commit: e7ea45f5bbeb60df526af8002e847451c888bd95
```

If you're using Cabal, it's probably `cabal.project`:

```yaml
source-repository-package
    type: git
    location: https://github.com/fjvallarino/monomer.git
    tag: e7ea45f5bbeb60df526af8002e847451c888bd95
```

**Comment by fjvallarino** [comment]
Note: the PR mentions an SDL2 issue that also happens only with GHC 9.2. You may run into the same problem, whose solution is currently using a specific SDL2 commit hash until a new version is released.

**Comment by fjvallarino** [comment]
As mentioned in the previous comment, the fix has already been merged into main, so I'll close the issue. Please re-open if needed or create a new one. Thanks!
